### ISSUE TITLE
Goal for this week 10/4

### ISSUE THREAD

**Issue by TwinIsland** [Burnham310/Octave#4]
## Functionality
@Tesseract22 @TwinIsland 
- [x] variable declaration
- [x] section channel combine
- [ ] interpolate mapper function
- [ ] pitch sequence sugar
- [x] nicer website

## Document/Frontend
@KugouHu 
- [ ] BNF/grammar document

## Interpolate Function
```
linear (idx: Int, n: Int): iFunc -> Int
```

## Expectation
```octave
// Tchaikovsky Theme

violin_sec = | do=1, chord=[do 3 5]:

<>[scale=/D 3 MAJ/, bpm=120, volume=80, instrument=50]

    // Intro Fanfare
    1.. 1... o'5..  o'1..    // Simple melody leading into the fanfare theme
    5... 6... 7... o'2...    // Ascending line towards dominant
    
    // Theme entrance (brass fanfare, slow tempo)
    o'3.. o'5.. o'6... o'2...    // Majestic chords rising
    1... 5... o'1... o'7... o'5..  o'5...    // Rhythmically strong fanfare

<buildup_start>[volume=80 linear]

    // Canon-like progression (celebratory)
    o'1.. o'3.. o'5.. o'chord... o'[5 7 o'2]...  // Chords overlaid with melodic fragments
    (5 o'6 o'5 o'7 o'5)...  // Rising motion
    
<buildup_start>[volume=70 linear, instrument=32]

    // Build-up to climax
    oo'2... ooo'1.. oo'5... oo'6... oo'7...  // Thickening texture, layering chords and melody

    // Climactic chords with cannon fire
    ooo'[1 5]... []... oo'[3 7]... ooo'1..  // Strong sustained chords with dramatic pauses for "cannons"
    ooo'2... ooo'5... ooo'7... ooo'[1 3 5]...   // Final climactic chord progression

<buildup-end>[volume=100 linear]

    // Ending sequence, return to initial theme
    o'2... o'5... o'6... o'5...  oo'1.. oo'5... oo'7...  // Resolved closing
    oo'[2 5]... oo'3... 

<buildup-end>[volume=100 linear]

   oo'5... oo'[1 3 5]...

<sec_end >[volume=0]
|

// section for bass
bass_sec = | :scale=/D 3 MAJ>, bpm=120, volume=80, instrument=23
 oo'[2 5]... oo'3... oo'5... oo'[1 3 5]...
|

// combine sections into chorus

main = violin_sec & bass_sec
```

**Comment by Tesseract22** [comment]
Some thoughts on the newly proposed `(1 2 3)..` construct:

## list 
We can elevate it from a syntactic sugar to an actual construct.
### Syntax
```BNF
<list> ::= ( <Exp>* )
```
### Semantic
All element in the list must have the same type. A list type is therefore aware of its base type, but not length, which we define as a runtime value. Note that this will make our type system recursive.
(We currently already a nestable data structure `Chord`. But our `Chord` can only have `Pitch` or `Chord` as its base type, and we flatten it anyway during evaluation, so it is not recursive type-wise)

We can then have some list operators. To go back to the original example, we can define a `map` operator `<$>` (stolen from `Haskell`), where we can then write:
```
(1 2 o'3) <$> ...
```

##

**Comment by Tesseract22** [comment]
Another thing about Degree, Pitch, Int and Note.

In our language, `Degree` is an integer index into a `Scale`, which is a `Pitch`. Operators like `o'` and `#'` only make sense for `Pitch`, and not `Int` or even `Degree`: When we evaluate `o'1`, we first evaluate `1` into a `Pitch` (which is just the number of semitones from `C-1`), and add `12` to it. So really `o'1` is `o'(scale[1])`
However we currently do not distinguish between `Int`, `Degree`, or `Pitch`. Essentially `bpm=o'140` would pass the semantic analyzer.
